### ISSUE TITLE
datasource1,datasource2在哪里配置的？

### ISSUE THREAD

**Issue by pistol-gao** [jfaster/mango-example#1]
在spring配置中只看到一个datasource配置，MyDataSourceRouter 这部分代码的意思是开发者自己做选择吗？

**Comment by liangyanghe** [comment]
datasource1, datasource2可以在spring中配置，也能直接写在代码中。MyDataSourceRouter是开发者自己实现的分库算法。
具体实例请参见：https://github.com/liangyanghe/letv-payorder

**Comment by pistol-gao** [comment]
OK，明白了。感谢感谢，开源出来实在太nice了

**Comment by liangyanghe** [comment]
以后会有一些修改和展示功能加强，请多提意见

**Comment by wuwenyu19860817** [comment]
你这个事务  是不是只能手动搞啊？？？？

**Comment by wuwenyu19860817** [comment]
没有注解完成单数据源的事务？？？

**Comment by liangyanghe** [comment]
自己写个aop，集成入spring很容易的，我们也在考虑在之后的版本多写一些spring插件

**Comment by wuwenyu19860817** [comment]
有没有现成的代码 我这边已经集成到项目了  发现事务要是手动的

**Comment by wuwenyu19860817** [comment]
这个框架挺好的

**Comment by liangyanghe** [comment]
有，我周一去找同事要一个，留个邮箱，我把核心代码发给你

**Comment by wuwenyu19860817** [comment]
524220752@qq.com
